### ISSUE TITLE
Trouble w/ version of CRTM

### ISSUE THREAD

**Issue by rtodling** [GEOS-ESM/jedi_bundle#29]
We presently have a problem w/ the bundle here and the version of CRTM it picks. I have an issue in the jedi/crtm repo trying to identify a better version of CRTM to use. Presently, the c-tests are failing due to an inconsistent Aerosol coefficient file.

When I find out what version we should use this will need to be updated here.

**Comment by Dooruk** [comment]
Ok, please let me know what version you are trying to install. 

The default CRTM version is defined below, but you can change that manually before building your bundle, while choosing which repos to build. **I think** a problem might arise when the CRTM version you are requesting is old and not compatible with the current develop JEDI repos.

https://github.com/GEOS-ESM/jedi_bundle/blob/develop/src/jedi_bundle/config/build.yaml

**Comment by Dooruk** [comment]
@rtodling , I need your help with this. Currently, Swell tier2 tests involve building the latest JEDI every night and and there is a step during the build where CRTM coefficients need to be obtained from a server. See [this comment](https://github.com/orgs/JCSDA-internal/discussions/77#discussioncomment-7359929) for a detailed description. I see @danholdaway tried to resolve this issue with this [PR](https://github.com/GEOS-ESM/jedi_bundle/pull/25) but the tier2 CI build still fails while attempting to download CRTM coefficients.

Here is what I need to know: 

- What version of CRTM should we be using now? 
- What CRTM version are we aiming for next and how soon? I will mention this issue in the JEDI Wednesdays group as well.

Bonus, error message below:

<img width="1367" alt="Screenshot 2024-02-11 at 2 22 01 PM" src="https://github.com/GEOS-ESM/jedi_bundle/assets/38666458/eb3dd0df-bcfb-41b8-91c5-a6c18d763bb4">

**Comment by Dooruk** [comment]
@rtodling, I will change the YAML entries here:

https://github.com/GEOS-ESM/jedi_bundle/blob/develop/src/jedi_bundle/config/platforms/nccs_discover.yaml

`crtm_coeffs_path` will be the `advda` directory
`crtm_coeffs_version` will be tested with `v2.4.1-jedi.1`

So I will just need to download and store the crtm_coefficients, just FYI.

**Comment by rtodling** [comment]
Hi Doruk,

This looks good to me - I will also generate the CRTM surf files later today or tomorrow and point you to them so we can have that closed. Thanks for this.
